version: "3.8"
services:
  frontend:
    image: ghcr.io/paul-austin-oswego-csc480-hci521/oz-csc-480-hci-521-spring-2026-public/frontend:${VERSION:-latest}
    container_name: frontend-csc480-prod-container
    ports:
      - "7000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs/frontend:/var/log/frontend
    restart: unless-stopped
    
  backend-finish:
    image: ghcr.io/paul-austin-oswego-csc480-hci521/oz-csc-480-hci-521-spring-2026-public/backend-finish:${VERSION:-latest}
    container_name: backend-finish-csc480-prod-container
    ports:
      - "7001:9080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs/backend:/logs
    restart: unless-stopped