name: Deploy to Moxie Server
on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version to deploy (e.g. v1.2.3)"
                required: true
env:
    VERSION: ${{ inputs.version || 'latest' }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            
            - name: Deploy to server
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.MOXIE_DEPLOY_HOST_CSC480 }}
                  username: ${{ secrets.MOXIE_DEPLOY_USERNAME_CSC480 }}
                  key: ${{ secrets.MOXIE_DEPLOY_KEY_CSC480 }}
                  script: |
                      mkdir -p ~/CSC480/production/
                      cd ~/CSC480/production/
                     
                      curl -fsSL https://raw.githubusercontent.com/Paul-Austin-Oswego-CSC480-HCI521/-OZ-CSC-480-HCI-521-Spring-2026-Public/main/docker-compose.yml -o docker-compose.yml

                      VERSION=${{ env.VERSION }} docker-compose pull
                      docker-compose down
                      VERSION=${{ env.VERSION }} docker-compose up -d
                      docker-compose ps